---
-  name: ELK playbook
   hosts: 10.1.0.4
   become: true
   tasks:

   -  name: Install docker via apt
      apt:
        update_cache: yes
        name: docker.io
        state: present

   -  name: Install python3-pip via apt
      apt:
        name: python3-pip
        state: present

   -  name: Install Python Docker Module
      pip:
        name: docker
        state: present

   - name: Increase virtual memory
     command: sysctl -w vm.max_map_count=262144

   - name: Use more memory
     sysctl:
       name: net.core.rmem_default
       value: 262144
       state: present
       reload: yes

   -  name: Download and launch a docker web container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 9200:9200
          - 5601:5601
          - 5044:5044

   -  name: Enable docker service
      systemd:
        name: docker
        enabled: yes