---
-  name: Install and Configure Filebeat
   hosts: 10.0.0.8, 10.0.0.11
   become: true
   tasks:

   - name: Download Filebeat
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

   - name: Install Filebeat
     command: dpkg -i filebeat-7.4.0-amd64.deb

   - name: Copy filbeat.yml
     copy:
       src: /etc/ansible/filebeat.yml
       dest: /etc/filebeat/filebeat.yml

   - name: Enable system module
     command: filebeat modules enable system

   - name: Run Filebeat setup
     command: filebeat setup

   - name: Start the Filebeat service
     command: service filebeat start

   - name: Enable Filebeat on boot
     ansible.builtin.systemd:
       name: filebeat
       state: started
       enabled: yes
       masked: no