---
-  name: Install and Configure Metricbeat
   hosts: 10.0.0.8, 10.0.0.11
   become: true
   tasks:

   - name: Download Metricbeat
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

   - name: Install Metricbeat
     command: dpkg -i metricbeat-7.6.1-amd64.deb

   - name: Copy metricbeat.yml
     copy:
       src: /etc/ansible/metricbeat.yml
       dest: /etc/metricbeat/metricbeat.yml

   - name: Enable system module
     command: metricbeat modules enable docker

   - name: Run Metricbeat setup
     command: metricbeat setup

   - name: Start the Metricbeat service
     command: service metricbeat start

   - name: Enable Metricbeat on boot
     ansible.builtin.systemd:
       name: metricbeat
       state: started
       enabled: yes
       masked: no