---
-  name: My first playbook
   hosts: all
   become: true
   tasks:

   -  name: Install docker via apt
      apt:
        name: docker
        state: present

   -  name: Install python3-pip via apt
      apt:
        name: python3-pip
        state: present